---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Remove Zabbix 4.4 repository on Ubuntu 20.04 Focal
      ansible.builtin.apt_repository:
        repo: deb http://repo.zabbix.com/zabbix/4.4/ubuntu/ focal main
        state: absent
    - name: Remove Zabbix source 4.4 repository on Ubuntu 20.04 Focal
      ansible.builtin.apt_repository:
        repo: deb-src http://repo.zabbix.com/zabbix/4.4/ubuntu/ focal main
        state: absent
    - name: Delete Zabbix 4.4 repo file
      file:
        state: absent
        path: /etc/apt/sources.list.d/repo_zabbix_com_zabbix_4_4_ubuntu.list

    - name: Remove Zabbix 4.4 repository on Ubuntu 18.04 Bionic
      ansible.builtin.apt_repository:
        repo: deb http://repo.zabbix.com/zabbix/4.4/ubuntu/ bionic main
        state: absent
    - name: Remove Zabbix source 4.4 repository on Ubuntu 18.04 Bionic
      ansible.builtin.apt_repository:
        repo: deb-src http://repo.zabbix.com/zabbix/4.4/ubuntu/ bionic main
        state: absent
    - name: Delete Zabbix 4.4 repo file
      file:
        state: absent
        path: /etc/apt/sources.list.d/repo_zabbix_com_zabbix_4_4_ubuntu.list

    - name: Remove Zabbix 4.4 repository on Debian 10 Buster
      ansible.builtin.apt_repository:
        repo: deb http://repo.zabbix.com/zabbix/4.4/debian/ buster main
        state: absent
    - name: Remove Zabbix source 4.4 repository on Debian 10 Buster
      ansible.builtin.apt_repository:
        repo: deb-src http://repo.zabbix.com/zabbix/4.4/debian/ buster main
        state: absent
    - name: Delete Zabbix 4.4 repo file
      file:
        state: absent
        path: /etc/apt/sources.list.d/repo_zabbix_com_zabbix_4_4_debian.list
